# Generated by Django 5.0.7 on 2024-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('creatioDate', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
                ('serialNumber', models.CharField(max_length=15)),
                ('vehicleType', models.CharField(choices=[('UTL', 'Utilitário'), ('LDT', 'VUC'), ('SUT', 'Toco'), ('TRK', 'Truck'), ('TST', 'Bitruck'), ('TCR', 'Cavalo mecânico simples'), ('STR', 'Carreta')], max_length=3)),
                ('creatioDate', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
