# Generated by Django 5.0.7 on 2024-08-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_client_cnpj_vehicle_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serialNumber',
            field=models.CharField(max_length=10),
        ),
    ]
