# Generated by Django 5.0.7 on 2024-08-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_owner_vehicle_client_alter_client_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='creatioDate',
            new_name='creationDate',
        ),
    ]
