# Generated by Django 5.0.7 on 2024-08-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_creatiodate_client_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.client'),
        ),
    ]
