# Generated by Django 5.0.7 on 2024-08-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_vehicle_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='creatioDate',
            new_name='creationDate',
        ),
    ]
