# Generated by Django 5.0.7 on 2024-08-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_rename_creatiodate_vehicle_creationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onixsat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.BigIntegerField(blank=True, null=True)),
                ('veiid', models.CharField(blank=True, max_length=11, null=True)),
                ('lat', models.CharField(blank=True, max_length=30, null=True)),
                ('lon', models.CharField(blank=True, max_length=30, null=True)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('vel', models.BigIntegerField(blank=True, null=True)),
                ('odm', models.BigIntegerField(blank=True, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('mun', models.CharField(blank=True, max_length=150, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
                ('evt4', models.CharField(blank=True, max_length=50, null=True)),
                ('evt5', models.CharField(blank=True, max_length=45, null=True)),
                ('evt14', models.CharField(blank=True, max_length=50, null=True)),
                ('evt16', models.CharField(blank=True, max_length=45, null=True)),
                ('evt17', models.CharField(blank=True, max_length=45, null=True)),
                ('evt28', models.CharField(blank=True, max_length=45, null=True)),
                ('evt29', models.CharField(blank=True, max_length=45, null=True)),
                ('evt30', models.CharField(blank=True, max_length=45, null=True)),
                ('evt31', models.CharField(blank=True, max_length=45, null=True)),
                ('evt84', models.CharField(blank=True, max_length=45, null=True)),
                ('evt98', models.CharField(blank=True, max_length=45, null=True)),
                ('evtg', models.CharField(blank=True, max_length=45, null=True)),
                ('dmac', models.TextField(blank=True, null=True)),
                ('st1', models.IntegerField(blank=True, null=True)),
                ('pr', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('ativo_ocorrencia', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'onixsat',
                'managed': False,
            },
        ),
    ]
